[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name          syslog
    Tag           vmware.syslog
    Mode          tcp
    Listen        0.0.0.0
    Port          1514
    Parser        syslog-auto

[INPUT]
    Name          syslog
    Tag           vmware.syslog
    Mode          udp
    Listen        0.0.0.0
    Port          1514
    Parser        syslog-auto

[FILTER]
    Name          lua
    Match         vmware.syslog
    script        /fluent-bit/etc/vmware.lua
    call          normalize_vmware

[OUTPUT]
    Name                 opensearch
    Match                vmware.syslog
    Host                 opensearch
    Port                 9200
    HTTP_User            ${OPENSEARCH_USERNAME}
    HTTP_Passwd          ${OPENSEARCH_PASSWORD}
    TLS                  On
    TLS.Verify           Off
    Suppress_Type_Name   On
    Replace_Dots         On
    Logstash_Format      On
    Logstash_Prefix_Key  index_prefix
    Logstash_DateFormat  %Y.%m.%d
    Trace_Error          On
