[PARSER]
    Name        syslog-auto
    Format      regex
    Regex       ^\<(?<pri>[0-9]+)\>(?:1 (?<time5424>[^ ]+) (?<hostname5424>[^ ]+) (?<appname>[^ ]+) (?<procid>[^ ]+) (?<msgid>[^ ]+) (?<structured_data>(?:\-|\[[^\]]*\])) ?|(?<time3164>[A-Z][a-z]{2} +[0-9]{1,2} [0-9:]{8}) (?<hostname3164>[^ ]+) (?<ident>[A-Za-z0-9_\/\.\-]+)(?:\[(?<pid>[0-9]+)\])?:? ?)(?<syslog_message>.*)$

[PARSER]
    Name        syslog-rfc3164
    Format      regex
    Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<hostname>[^ ]*) (?<ident>[A-Za-z0-9_\/\.\-]+)(?:\[(?<pid>[0-9]+)\])?: (?<message>.*)$
    Time_Key    time
    Time_Format %b %d %H:%M:%S
    Time_Keep   On

[PARSER]
    Name        syslog-rfc5424
    Format      regex
    Regex       ^\<(?<pri>[0-9]+)\>1 (?<time>[^ ]+) (?<hostname>[^ ]+) (?<appname>[^ ]+) (?<procid>[^ ]+) (?<msgid>[^ ]+) (?<structured_data>(?:\-|\[.*\])) ?(?<message>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   On
