import type {
  Incident,
  ChatSession,
  ChatMessage,
  Evidence,
  ChangeImpactResult,
  ToolMeta,
  ToolHealthStatus,
  IncidentTimelineEntry,
} from "@opspilot/shared-types";

export const mockIncidents: Incident[] = [
  {
    id: "INC-20260405-001",
    title: "ESXi 主机 esxi-node03 CPU 使用率持续 >95%",
    status: "analyzing",
    severity: "high",
    source: "vmware-monitor",
    source_type: "metric_anomaly",
    affected_objects: [
      { object_type: "HostSystem", object_id: "host-33", object_name: "esxi-node03.corp.local" },
      { object_type: "VirtualMachine", object_id: "vm-201", object_name: "app-server-01" },
      { object_type: "VirtualMachine", object_id: "vm-202", object_name: "app-server-02" },
    ],
    first_seen_at: "2026-04-05T08:12:00Z",
    last_updated_at: "2026-04-05T08:45:00Z",
    owner: "zhangsan",
    ai_analysis_triggered: true,
    root_cause_candidates: [
      {
        id: "rc-1",
        description: "VM app-server-01 的 Java 进程发生 Full GC 风暴导致 CPU 飙升",
        confidence: 0.87,
        evidence_refs: ["evd-001", "evd-002", "evd-003"],
        category: "application",
      },
      {
        id: "rc-2",
        description: "esxi-node03 在 08:00 执行了存储 vMotion，导致临时资源争用",
        confidence: 0.62,
        evidence_refs: ["evd-004"],
        category: "change_correlation",
      },
    ],
    recommended_actions: [
      "检查 app-server-01 JVM 堆内存配置和 GC 日志",
      "对 esxi-node03 当前 VM 负载做平衡评估",
      "考虑将 app-server-01 迁移到低负载主机",
    ],
    evidence_refs: ["evd-001", "evd-002", "evd-003", "evd-004"],
    summary: "esxi-node03 自 08:12 起 CPU 利用率持续高于 95%，初步分析指向 app-server-01 的 Java 进程异常。",
  },
  {
    id: "INC-20260405-002",
    title: "Datastore ds-nfs-prod01 可用容量低于 10%",
    status: "pending_action",
    severity: "medium",
    source: "vmware-monitor",
    source_type: "threshold_alert",
    affected_objects: [
      { object_type: "Datastore", object_id: "ds-45", object_name: "ds-nfs-prod01" },
    ],
    first_seen_at: "2026-04-05T07:30:00Z",
    last_updated_at: "2026-04-05T08:00:00Z",
    owner: null,
    ai_analysis_triggered: true,
    root_cause_candidates: [
      {
        id: "rc-3",
        description: "近 7 天快照未清理，占用约 800GB 空间",
        confidence: 0.91,
        evidence_refs: ["evd-005"],
        category: "capacity",
      },
    ],
    recommended_actions: [
      "清理过期快照（预计释放 800GB）",
      "检查快照策略配置",
    ],
    evidence_refs: ["evd-005"],
    summary: "ds-nfs-prod01 可用空间仅剩 9.2%，主因是 VM 快照未按策略清理。",
  },
  {
    id: "INC-20260404-005",
    title: "集群 cluster-prod-az1 HA 故障切换事件",
    status: "resolved",
    severity: "critical",
    source: "vmware-event",
    source_type: "ha_event",
    affected_objects: [
      { object_type: "ClusterComputeResource", object_id: "cluster-10", object_name: "cluster-prod-az1" },
      { object_type: "HostSystem", object_id: "host-31", object_name: "esxi-node01.corp.local" },
    ],
    first_seen_at: "2026-04-04T23:15:00Z",
    last_updated_at: "2026-04-05T01:30:00Z",
    owner: "lisi",
    ai_analysis_triggered: true,
    root_cause_candidates: [
      {
        id: "rc-4",
        description: "esxi-node01 网卡 vmnic2 链路中断引发 HA isolation",
        confidence: 0.95,
        evidence_refs: ["evd-006", "evd-007"],
        category: "hardware",
      },
    ],
    recommended_actions: [
      "检查 esxi-node01 物理网卡和交换机端口",
      "确认 HA 隔离响应策略是否需要调整",
    ],
    evidence_refs: ["evd-006", "evd-007"],
    summary: "esxi-node01 网络隔离触发 HA 切换，受影响 VM 已在其他主机重新启动。",
  },
];

export const mockEvidences: Evidence[] = [
  {
    evidence_id: "evd-001",
    source: "vmware-monitor",
    source_type: "metric",
    object_type: "HostSystem",
    object_id: "host-33",
    timestamp: "2026-04-05T08:12:00Z",
    summary: "esxi-node03 CPU usage 97.3%",
    raw_ref: null,
    confidence: 0.98,
    correlation_key: "host-33:INC-20260405-001",
  },
  {
    evidence_id: "evd-002",
    source: "vmware-monitor",
    source_type: "metric",
    object_type: "VirtualMachine",
    object_id: "vm-201",
    timestamp: "2026-04-05T08:15:00Z",
    summary: "app-server-01 CPU ready time 12.5%，显著偏高",
    raw_ref: null,
    confidence: 0.94,
    correlation_key: "vm-201:INC-20260405-001",
  },
  {
    evidence_id: "evd-003",
    source: "rag-service",
    source_type: "kb",
    object_type: "KnowledgeArticle",
    object_id: "kb-jvm-gc",
    timestamp: "2026-04-05T08:20:00Z",
    summary: "VMware KB: Java Full GC 导致 vCPU 高占用的诊断方法",
    raw_ref: null,
    confidence: 0.82,
    correlation_key: null,
  },
  {
    evidence_id: "evd-004",
    source: "vmware-event",
    source_type: "event",
    object_type: "VirtualMachine",
    object_id: "vm-203",
    timestamp: "2026-04-05T08:00:00Z",
    summary: "vm-203 storage vMotion completed at 08:05",
    raw_ref: null,
    confidence: 0.75,
    correlation_key: "host-33:INC-20260405-001",
  },
  {
    evidence_id: "evd-005",
    source: "vmware-monitor",
    source_type: "metric",
    object_type: "Datastore",
    object_id: "ds-45",
    timestamp: "2026-04-05T07:30:00Z",
    summary: "ds-nfs-prod01 usage 90.8%, snapshots 占 820GB",
    raw_ref: null,
    confidence: 0.97,
    correlation_key: "ds-45:INC-20260405-002",
  },
  {
    evidence_id: "evd-006",
    source: "vmware-event",
    source_type: "event",
    object_type: "HostSystem",
    object_id: "host-31",
    timestamp: "2026-04-04T23:15:00Z",
    summary: "esxi-node01 reported HA host isolation",
    raw_ref: null,
    confidence: 0.99,
    correlation_key: "host-31:INC-20260404-005",
  },
  {
    evidence_id: "evd-007",
    source: "vmware-event",
    source_type: "event",
    object_type: "HostSystem",
    object_id: "host-31",
    timestamp: "2026-04-04T23:14:30Z",
    summary: "vmnic2 link down event on esxi-node01",
    raw_ref: null,
    confidence: 0.99,
    correlation_key: "host-31:INC-20260404-005",
  },
];

export const mockIncidentTimeline: IncidentTimelineEntry[] = [
  { timestamp: "2026-04-05T08:12:00Z", type: "event", summary: "告警触发：esxi-node03 CPU > 95%", agent: "IncidentDetectionAgent" },
  { timestamp: "2026-04-05T08:12:05Z", type: "analysis", summary: "自动创建故障事件 INC-20260405-001", agent: "Orchestrator" },
  { timestamp: "2026-04-05T08:12:10Z", type: "analysis", summary: "开始采集证据：主机指标、VM 指标、近期事件", agent: "EvidenceCollectionAgent" },
  { timestamp: "2026-04-05T08:15:00Z", type: "analysis", summary: "证据采集完成，共 4 条证据", agent: "EvidenceCollectionAgent" },
  { timestamp: "2026-04-05T08:15:30Z", type: "analysis", summary: "知识库检索：命中 KB-JVM-GC 文档", agent: "KBRetrievalAgent" },
  { timestamp: "2026-04-05T08:16:00Z", type: "analysis", summary: "根因分析完成：2 个候选根因", agent: "RCAAgent" },
  { timestamp: "2026-04-05T08:16:30Z", type: "notification", summary: "通知值班人 zhangsan", agent: "NotificationAgent" },
  { timestamp: "2026-04-05T08:45:00Z", type: "action", summary: "值班人查看并开始处理", agent: "Human" },
];

export const mockChatSessions: ChatSession[] = [
  { id: "sess-001", title: "esxi-node03 CPU 告警分析", created_at: "2026-04-05T08:20:00Z", updated_at: "2026-04-05T08:45:00Z", tags: ["故障诊断", "VMware"], message_count: 6 },
  { id: "sess-002", title: "ds-nfs-prod01 容量问题", created_at: "2026-04-05T07:35:00Z", updated_at: "2026-04-05T07:55:00Z", tags: ["容量", "存储"], message_count: 4 },
  { id: "sess-003", title: "迁移 app-server-01 的影响分析", created_at: "2026-04-04T16:00:00Z", updated_at: "2026-04-04T16:30:00Z", tags: ["变更分析"], message_count: 3 },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-001",
    session_id: "sess-001",
    role: "user",
    content: "esxi-node03 CPU 一直很高，帮我分析一下原因。",
    timestamp: "2026-04-05T08:20:00Z",
  },
  {
    id: "msg-002",
    session_id: "sess-001",
    role: "assistant",
    content: "我已启动对 esxi-node03 的诊断分析。正在采集主机指标、VM 资源使用和近期变更事件...",
    timestamp: "2026-04-05T08:20:05Z",
    agent_name: "Orchestrator",
    tool_traces: [
      { tool_name: "vmware.get_host_detail", gateway: "vmware-skill-gateway", input_summary: '{"host_id": "host-33"}', output_summary: "CPU: 97.3%, Memory: 82.1%, VMs: 12", duration_ms: 320, status: "success", timestamp: "2026-04-05T08:20:06Z" },
      { tool_name: "vmware.query_metrics", gateway: "vmware-skill-gateway", input_summary: '{"host_id": "host-33", "metric": "cpu.usage"}', output_summary: "1h trend: 72% -> 97%", duration_ms: 450, status: "success", timestamp: "2026-04-05T08:20:07Z" },
      { tool_name: "vmware.query_events", gateway: "vmware-skill-gateway", input_summary: '{"host_id": "host-33", "hours": 4}', output_summary: "3 events found", duration_ms: 280, status: "success", timestamp: "2026-04-05T08:20:08Z" },
    ],
  },
  {
    id: "msg-003",
    session_id: "sess-001",
    role: "assistant",
    content: "## 诊断结论\n\nesxi-node03 的 CPU 持续高位主要由 **app-server-01** 上的 Java 进程引起。过去 1 小时 CPU 从 72% 飙升至 97.3%。\n\n### 根因候选\n1. **app-server-01 Java Full GC 风暴** (置信度 87%)\n2. **08:00 存储 vMotion 引起的资源争用** (置信度 62%)\n\n### 建议动作\n- 检查 app-server-01 的 JVM 堆内存配置和 GC 日志\n- 对 esxi-node03 VM 负载进行平衡评估\n- 考虑将 app-server-01 迁移到低负载主机",
    timestamp: "2026-04-05T08:21:00Z",
    agent_name: "RCAAgent",
    evidence_refs: ["evd-001", "evd-002", "evd-003", "evd-004"],
    root_cause_candidates: [
      { description: "app-server-01 Java Full GC 风暴导致 CPU 飙升", confidence: 0.87 },
      { description: "存储 vMotion 引起临时资源争用", confidence: 0.62 },
    ],
    recommended_actions: [
      "检查 app-server-01 JVM 堆内存配置和 GC 日志",
      "对 esxi-node03 当前 VM 负载做平衡评估",
      "考虑将 app-server-01 迁移到低负载主机",
    ],
  },
  {
    id: "msg-004",
    session_id: "sess-001",
    role: "user",
    content: "如果要迁移 app-server-01，影响大吗？",
    timestamp: "2026-04-05T08:25:00Z",
  },
  {
    id: "msg-005",
    session_id: "sess-001",
    role: "assistant",
    content: "我来对 app-server-01 的迁移做一次变更影响分析...",
    timestamp: "2026-04-05T08:25:05Z",
    agent_name: "Orchestrator",
    tool_traces: [
      { tool_name: "change_impact.analyze", gateway: "change-impact-service", input_summary: '{"target": "vm-201", "action": "vm_migrate"}', output_summary: "risk_score: 45, risk_level: medium", duration_ms: 520, status: "success", timestamp: "2026-04-05T08:25:06Z" },
    ],
  },
  {
    id: "msg-006",
    session_id: "sess-001",
    role: "assistant",
    content: "## 变更影响分析\n\n迁移 app-server-01 的风险评估为 **中等** (风险评分 45/100)。\n\n### 影响对象\n- app-server-02 (同主机，资源会释放)\n- 目标主机需至少 8vCPU + 32GB 空闲\n\n### 建议\n- 建议在业务低峰期执行\n- 需要审批 → 可点击下方按钮发起执行申请",
    timestamp: "2026-04-05T08:25:30Z",
    agent_name: "ChangeCorrelationAgent",
    evidence_refs: ["evd-001", "evd-002"],
  },
];

export const mockChangeImpactResult: ChangeImpactResult = {
  analysis_id: "cia-001",
  target: { type: "VirtualMachine", id: "vm-201", name: "app-server-01" },
  action: "vm_migrate",
  risk_score: 45,
  risk_level: "medium",
  impacted_objects: [
    { object_type: "VirtualMachine", object_id: "vm-202", object_name: "app-server-02", impact_type: "resource_release", severity: "low" },
    { object_type: "HostSystem", object_id: "host-34", object_name: "esxi-node04", impact_type: "resource_consumption", severity: "medium" },
    { object_type: "Datastore", object_id: "ds-45", object_name: "ds-nfs-prod01", impact_type: "storage_path_change", severity: "low" },
  ],
  checks_required: [
    "目标主机资源充足性检查",
    "网络连通性检查",
    "存储兼容性检查",
    "DRS 规则冲突检查",
  ],
  rollback_plan: [
    "如迁移失败，VM 自动回退到原主机 esxi-node03",
    "确认原主机快照可用",
  ],
  approval_suggestion: "required",
  dependency_graph: [
    {
      id: "vm-201", name: "app-server-01", type: "VirtualMachine",
      children: [
        { id: "host-33", name: "esxi-node03 (source)", type: "HostSystem", children: [] },
        { id: "host-34", name: "esxi-node04 (target)", type: "HostSystem", children: [] },
        { id: "ds-45", name: "ds-nfs-prod01", type: "Datastore", children: [] },
      ],
    },
  ],
};

export const mockTools: ToolMeta[] = [
  { name: "vmware.get_vcenter_inventory", display_name: "查询 vCenter 清单", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 30, idempotent: true, version: "1.0.0", tags: ["vmware", "inventory"] },
  { name: "vmware.get_vm_detail", display_name: "查询虚拟机详情", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 30, idempotent: true, version: "1.0.0", tags: ["vmware", "inventory"] },
  { name: "vmware.get_host_detail", display_name: "查询主机详情", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 30, idempotent: true, version: "1.0.0", tags: ["vmware", "inventory"] },
  { name: "vmware.query_events", display_name: "查询事件", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 30, idempotent: true, version: "1.0.0", tags: ["vmware", "event"] },
  { name: "vmware.query_metrics", display_name: "查询性能指标", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 60, idempotent: true, version: "1.0.0", tags: ["vmware", "metric"] },
  { name: "vmware.vm_migrate", display_name: "迁移虚拟机", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "write", risk_level: "high", approval_required: true, timeout_seconds: 300, idempotent: false, version: "1.0.0", tags: ["vmware", "execution"] },
  { name: "vmware.create_snapshot", display_name: "创建快照", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "write", risk_level: "medium", approval_required: false, timeout_seconds: 120, idempotent: false, version: "1.0.0", tags: ["vmware", "snapshot"] },
  { name: "change_impact.analyze", display_name: "变更影响分析", category: "analysis", domain: "platform", provider: "change-impact-service", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 60, idempotent: true, version: "1.0.0", tags: ["analysis", "change"] },
];

export const mockToolHealth: ToolHealthStatus[] = [
  { name: "vmware-skill-gateway", provider: "vmware-skill-gateway", healthy: true, last_check: "2026-04-05T08:50:00Z", latency_ms: 45 },
  { name: "change-impact-service", provider: "change-impact-service", healthy: true, last_check: "2026-04-05T08:50:00Z", latency_ms: 32 },
  { name: "evidence-aggregator", provider: "evidence-aggregator", healthy: true, last_check: "2026-04-05T08:50:00Z", latency_ms: 28 },
  { name: "rag-service", provider: "rag-service", healthy: false, last_check: "2026-04-05T08:48:00Z", latency_ms: 0 },
];
