import type {
  Incident,
  ChatSession,
  ChatMessage,
  Evidence,
  ChangeImpactResult,
  ToolMeta,
  ToolHealthStatus,
  IncidentTimelineEntry,
  ApprovalRequest,
  NotificationItem,
  OnCallShift,
  AuditLog,
  KnowledgeArticle,
  KnowledgeImportJob,
  OpsPolicy,
  PolicyHitRecord,
  CaseArchive,
  AgentRun,
  UpgradePackage,
  UpgradeDeploymentRecord,
} from "@opspilot/shared-types";

export const mockIncidents: Incident[] = [
  {
    id: "INC-20260405-001",
    title: "ESXi 主机 esxi-node03 CPU 使用率持续 >95%",
    status: "analyzing",
    severity: "high",
    source: "vmware-monitor",
    source_type: "metric_anomaly",
    affected_objects: [
      { object_type: "HostSystem", object_id: "host-33", object_name: "esxi-node03.corp.local" },
      { object_type: "VirtualMachine", object_id: "vm-201", object_name: "app-server-01" },
      { object_type: "VirtualMachine", object_id: "vm-202", object_name: "app-server-02" },
    ],
    first_seen_at: "2026-04-05T08:12:00Z",
    last_updated_at: "2026-04-05T08:45:00Z",
    owner: "zhangsan",
    ai_analysis_triggered: true,
    root_cause_candidates: [
      {
        id: "rc-1",
        description: "VM app-server-01 的 Java 进程发生 Full GC 风暴导致 CPU 飙升",
        confidence: 0.87,
        evidence_refs: ["evd-001", "evd-002", "evd-003"],
        category: "application",
      },
      {
        id: "rc-2",
        description: "esxi-node03 在 08:00 执行了存储 vMotion，导致临时资源争用",
        confidence: 0.62,
        evidence_refs: ["evd-004"],
        category: "change_correlation",
      },
    ],
    recommended_actions: [
      "检查 app-server-01 JVM 堆内存配置和 GC 日志",
      "对 esxi-node03 当前 VM 负载做平衡评估",
      "考虑将 app-server-01 迁移到低负载主机",
    ],
    evidence_refs: ["evd-001", "evd-002", "evd-003", "evd-004"],
    summary: "esxi-node03 自 08:12 起 CPU 利用率持续高于 95%，初步分析指向 app-server-01 的 Java 进程异常。",
  },
  {
    id: "INC-20260405-002",
    title: "Datastore ds-nfs-prod01 可用容量低于 10%",
    status: "pending_action",
    severity: "medium",
    source: "vmware-monitor",
    source_type: "threshold_alert",
    affected_objects: [
      { object_type: "Datastore", object_id: "ds-45", object_name: "ds-nfs-prod01" },
    ],
    first_seen_at: "2026-04-05T07:30:00Z",
    last_updated_at: "2026-04-05T08:00:00Z",
    owner: null,
    ai_analysis_triggered: true,
    root_cause_candidates: [
      {
        id: "rc-3",
        description: "近 7 天快照未清理，占用约 800GB 空间",
        confidence: 0.91,
        evidence_refs: ["evd-005"],
        category: "capacity",
      },
    ],
    recommended_actions: [
      "清理过期快照（预计释放 800GB）",
      "检查快照策略配置",
    ],
    evidence_refs: ["evd-005"],
    summary: "ds-nfs-prod01 可用空间仅剩 9.2%，主因是 VM 快照未按策略清理。",
  },
  {
    id: "INC-20260404-005",
    title: "集群 cluster-prod-az1 HA 故障切换事件",
    status: "resolved",
    severity: "critical",
    source: "vmware-event",
    source_type: "ha_event",
    affected_objects: [
      { object_type: "ClusterComputeResource", object_id: "cluster-10", object_name: "cluster-prod-az1" },
      { object_type: "HostSystem", object_id: "host-31", object_name: "esxi-node01.corp.local" },
    ],
    first_seen_at: "2026-04-04T23:15:00Z",
    last_updated_at: "2026-04-05T01:30:00Z",
    owner: "lisi",
    ai_analysis_triggered: true,
    root_cause_candidates: [
      {
        id: "rc-4",
        description: "esxi-node01 网卡 vmnic2 链路中断引发 HA isolation",
        confidence: 0.95,
        evidence_refs: ["evd-006", "evd-007"],
        category: "hardware",
      },
    ],
    recommended_actions: [
      "检查 esxi-node01 物理网卡和交换机端口",
      "确认 HA 隔离响应策略是否需要调整",
    ],
    evidence_refs: ["evd-006", "evd-007"],
    summary: "esxi-node01 网络隔离触发 HA 切换，受影响 VM 已在其他主机重新启动。",
  },
];

export const mockEvidences: Evidence[] = [
  {
    evidence_id: "evd-001",
    source: "vmware-monitor",
    source_type: "metric",
    object_type: "HostSystem",
    object_id: "host-33",
    timestamp: "2026-04-05T08:12:00Z",
    summary: "esxi-node03 CPU usage 97.3%",
    raw_ref: null,
    confidence: 0.98,
    correlation_key: "host-33:INC-20260405-001",
  },
  {
    evidence_id: "evd-002",
    source: "vmware-monitor",
    source_type: "metric",
    object_type: "VirtualMachine",
    object_id: "vm-201",
    timestamp: "2026-04-05T08:15:00Z",
    summary: "app-server-01 CPU ready time 12.5%，显著偏高",
    raw_ref: null,
    confidence: 0.94,
    correlation_key: "vm-201:INC-20260405-001",
  },
  {
    evidence_id: "evd-003",
    source: "rag-service",
    source_type: "kb",
    object_type: "KnowledgeArticle",
    object_id: "kb-jvm-gc",
    timestamp: "2026-04-05T08:20:00Z",
    summary: "VMware KB: Java Full GC 导致 vCPU 高占用的诊断方法",
    raw_ref: null,
    confidence: 0.82,
    correlation_key: null,
  },
  {
    evidence_id: "evd-004",
    source: "vmware-event",
    source_type: "event",
    object_type: "VirtualMachine",
    object_id: "vm-203",
    timestamp: "2026-04-05T08:00:00Z",
    summary: "vm-203 storage vMotion completed at 08:05",
    raw_ref: null,
    confidence: 0.75,
    correlation_key: "host-33:INC-20260405-001",
  },
  {
    evidence_id: "evd-005",
    source: "vmware-monitor",
    source_type: "metric",
    object_type: "Datastore",
    object_id: "ds-45",
    timestamp: "2026-04-05T07:30:00Z",
    summary: "ds-nfs-prod01 usage 90.8%, snapshots 占 820GB",
    raw_ref: null,
    confidence: 0.97,
    correlation_key: "ds-45:INC-20260405-002",
  },
  {
    evidence_id: "evd-006",
    source: "vmware-event",
    source_type: "event",
    object_type: "HostSystem",
    object_id: "host-31",
    timestamp: "2026-04-04T23:15:00Z",
    summary: "esxi-node01 reported HA host isolation",
    raw_ref: null,
    confidence: 0.99,
    correlation_key: "host-31:INC-20260404-005",
  },
  {
    evidence_id: "evd-007",
    source: "vmware-event",
    source_type: "event",
    object_type: "HostSystem",
    object_id: "host-31",
    timestamp: "2026-04-04T23:14:30Z",
    summary: "vmnic2 link down event on esxi-node01",
    raw_ref: null,
    confidence: 0.99,
    correlation_key: "host-31:INC-20260404-005",
  },
];

export const mockIncidentTimeline: IncidentTimelineEntry[] = [
  { timestamp: "2026-04-05T08:12:00Z", type: "event", summary: "告警触发：esxi-node03 CPU > 95%", agent: "IncidentDetectionAgent" },
  { timestamp: "2026-04-05T08:12:05Z", type: "analysis", summary: "自动创建故障事件 INC-20260405-001", agent: "Orchestrator" },
  { timestamp: "2026-04-05T08:12:10Z", type: "analysis", summary: "开始采集证据：主机指标、VM 指标、近期事件", agent: "EvidenceCollectionAgent" },
  { timestamp: "2026-04-05T08:15:00Z", type: "analysis", summary: "证据采集完成，共 4 条证据", agent: "EvidenceCollectionAgent" },
  { timestamp: "2026-04-05T08:15:30Z", type: "analysis", summary: "知识库检索：命中 KB-JVM-GC 文档", agent: "KBRetrievalAgent" },
  { timestamp: "2026-04-05T08:16:00Z", type: "analysis", summary: "根因分析完成：2 个候选根因", agent: "RCAAgent" },
  { timestamp: "2026-04-05T08:16:30Z", type: "notification", summary: "通知值班人 zhangsan", agent: "NotificationAgent" },
  { timestamp: "2026-04-05T08:45:00Z", type: "action", summary: "值班人查看并开始处理", agent: "Human" },
];

export const mockChatSessions: ChatSession[] = [
  { id: "sess-001", title: "esxi-node03 CPU 告警分析", created_at: "2026-04-05T08:20:00Z", updated_at: "2026-04-05T08:45:00Z", tags: ["故障诊断", "VMware"], message_count: 6 },
  { id: "sess-002", title: "ds-nfs-prod01 容量问题", created_at: "2026-04-05T07:35:00Z", updated_at: "2026-04-05T07:55:00Z", tags: ["容量", "存储"], message_count: 4 },
  { id: "sess-003", title: "迁移 app-server-01 的影响分析", created_at: "2026-04-04T16:00:00Z", updated_at: "2026-04-04T16:30:00Z", tags: ["变更分析"], message_count: 3 },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-001",
    session_id: "sess-001",
    role: "user",
    content: "esxi-node03 CPU 一直很高，帮我分析一下原因。",
    timestamp: "2026-04-05T08:20:00Z",
  },
  {
    id: "msg-002",
    session_id: "sess-001",
    role: "assistant",
    content: "我已启动对 esxi-node03 的诊断分析。正在采集主机指标、VM 资源使用和近期变更事件...",
    timestamp: "2026-04-05T08:20:05Z",
    agent_name: "Orchestrator",
    tool_traces: [
      { tool_name: "vmware.get_host_detail", gateway: "vmware-skill-gateway", input_summary: '{"host_id": "host-33"}', output_summary: "CPU: 97.3%, Memory: 82.1%, VMs: 12", duration_ms: 320, status: "success", timestamp: "2026-04-05T08:20:06Z" },
      { tool_name: "vmware.query_metrics", gateway: "vmware-skill-gateway", input_summary: '{"host_id": "host-33", "metric": "cpu.usage"}', output_summary: "1h trend: 72% -> 97%", duration_ms: 450, status: "success", timestamp: "2026-04-05T08:20:07Z" },
      { tool_name: "vmware.query_events", gateway: "vmware-skill-gateway", input_summary: '{"host_id": "host-33", "hours": 4}', output_summary: "3 events found", duration_ms: 280, status: "success", timestamp: "2026-04-05T08:20:08Z" },
    ],
  },
  {
    id: "msg-003",
    session_id: "sess-001",
    role: "assistant",
    content: "## 诊断结论\n\nesxi-node03 的 CPU 持续高位主要由 **app-server-01** 上的 Java 进程引起。过去 1 小时 CPU 从 72% 飙升至 97.3%。\n\n### 根因候选\n1. **app-server-01 Java Full GC 风暴** (置信度 87%)\n2. **08:00 存储 vMotion 引起的资源争用** (置信度 62%)\n\n### 建议动作\n- 检查 app-server-01 的 JVM 堆内存配置和 GC 日志\n- 对 esxi-node03 VM 负载进行平衡评估\n- 考虑将 app-server-01 迁移到低负载主机",
    timestamp: "2026-04-05T08:21:00Z",
    agent_name: "RCAAgent",
    evidence_refs: ["evd-001", "evd-002", "evd-003", "evd-004"],
    root_cause_candidates: [
      { description: "app-server-01 Java Full GC 风暴导致 CPU 飙升", confidence: 0.87 },
      { description: "存储 vMotion 引起临时资源争用", confidence: 0.62 },
    ],
    recommended_actions: [
      "检查 app-server-01 JVM 堆内存配置和 GC 日志",
      "对 esxi-node03 当前 VM 负载做平衡评估",
      "考虑将 app-server-01 迁移到低负载主机",
    ],
  },
  {
    id: "msg-004",
    session_id: "sess-001",
    role: "user",
    content: "如果要迁移 app-server-01，影响大吗？",
    timestamp: "2026-04-05T08:25:00Z",
  },
  {
    id: "msg-005",
    session_id: "sess-001",
    role: "assistant",
    content: "我来对 app-server-01 的迁移做一次变更影响分析...",
    timestamp: "2026-04-05T08:25:05Z",
    agent_name: "Orchestrator",
    tool_traces: [
      { tool_name: "change_impact.analyze", gateway: "change-impact-service", input_summary: '{"target": "vm-201", "action": "vm_migrate"}', output_summary: "risk_score: 45, risk_level: medium", duration_ms: 520, status: "success", timestamp: "2026-04-05T08:25:06Z" },
    ],
  },
  {
    id: "msg-006",
    session_id: "sess-001",
    role: "assistant",
    content: "## 变更影响分析\n\n迁移 app-server-01 的风险评估为 **中等** (风险评分 45/100)。\n\n### 影响对象\n- app-server-02 (同主机，资源会释放)\n- 目标主机需至少 8vCPU + 32GB 空闲\n\n### 建议\n- 建议在业务低峰期执行\n- 需要审批 → 可点击下方按钮发起执行申请",
    timestamp: "2026-04-05T08:25:30Z",
    agent_name: "ChangeCorrelationAgent",
    evidence_refs: ["evd-001", "evd-002"],
  },
];

export const mockChangeImpactResult: ChangeImpactResult = {
  analysis_id: "cia-001",
  target: {
    target_type: "VirtualMachine",
    target_id: "vm-201",
    environment: "prod",
    type: "VirtualMachine",
    id: "vm-201",
    name: "app-server-01",
  },
  action: "vm_migrate",
  risk_score: 45,
  risk_level: "medium",
  impacted_objects: [
    { object_type: "VirtualMachine", object_id: "vm-202", object_name: "app-server-02", impact_type: "resource_release", severity: "low" },
    { object_type: "HostSystem", object_id: "host-34", object_name: "esxi-node04", impact_type: "resource_consumption", severity: "medium" },
    { object_type: "Datastore", object_id: "ds-45", object_name: "ds-nfs-prod01", impact_type: "storage_path_change", severity: "low" },
  ],
  checks_required: [
    "目标主机资源充足性检查",
    "网络连通性检查",
    "存储兼容性检查",
    "DRS 规则冲突检查",
  ],
  rollback_plan: [
    "如迁移失败，VM 自动回退到原主机 esxi-node03",
    "确认原主机快照可用",
  ],
  approval_suggestion: "required",
  dependency_graph: [
    {
      id: "vm-201", name: "app-server-01", type: "VirtualMachine",
      children: [
        { id: "host-33", name: "esxi-node03 (source)", type: "HostSystem", children: [] },
        { id: "host-34", name: "esxi-node04 (target)", type: "HostSystem", children: [] },
        { id: "ds-45", name: "ds-nfs-prod01", type: "Datastore", children: [] },
      ],
    },
  ],
};

export const mockTools: ToolMeta[] = [
  { name: "vmware.get_vcenter_inventory", display_name: "查询 vCenter 清单", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 30, idempotent: true, version: "1.0.0", tags: ["vmware", "inventory"] },
  { name: "vmware.get_vm_detail", display_name: "查询虚拟机详情", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 30, idempotent: true, version: "1.0.0", tags: ["vmware", "inventory"] },
  { name: "vmware.get_host_detail", display_name: "查询主机详情", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 30, idempotent: true, version: "1.0.0", tags: ["vmware", "inventory"] },
  { name: "vmware.query_events", display_name: "查询事件", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 30, idempotent: true, version: "1.0.0", tags: ["vmware", "event"] },
  { name: "vmware.query_metrics", display_name: "查询性能指标", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 60, idempotent: true, version: "1.0.0", tags: ["vmware", "metric"] },
  { name: "vmware.vm_migrate", display_name: "迁移虚拟机", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "write", risk_level: "high", approval_required: true, timeout_seconds: 300, idempotent: false, version: "1.0.0", tags: ["vmware", "execution"] },
  { name: "vmware.create_snapshot", display_name: "创建快照", category: "vmware", domain: "infrastructure", provider: "vmware-skill-gateway", action_type: "write", risk_level: "medium", approval_required: false, timeout_seconds: 120, idempotent: false, version: "1.0.0", tags: ["vmware", "snapshot"] },
  { name: "change_impact.analyze", display_name: "变更影响分析", category: "analysis", domain: "platform", provider: "change-impact-service", action_type: "read", risk_level: "low", approval_required: false, timeout_seconds: 60, idempotent: true, version: "1.0.0", tags: ["analysis", "change"] },
];

export const mockToolHealth: ToolHealthStatus[] = [
  { name: "vmware-skill-gateway", provider: "vmware-skill-gateway", healthy: true, last_check: "2026-04-05T08:50:00Z", latency_ms: 45 },
  { name: "change-impact-service", provider: "change-impact-service", healthy: true, last_check: "2026-04-05T08:50:00Z", latency_ms: 32 },
  { name: "evidence-aggregator", provider: "evidence-aggregator", healthy: true, last_check: "2026-04-05T08:50:00Z", latency_ms: 28 },
  { name: "rag-service", provider: "rag-service", healthy: false, last_check: "2026-04-05T08:48:00Z", latency_ms: 0 },
];

// ── P1 Mock Data ─────────────────────────────────────────────────────────────

export const mockApprovals: ApprovalRequest[] = [
  {
    id: "APR-20260405-001",
    title: "迁移 app-server-01 到 esxi-node04",
    description: "因 esxi-node03 CPU 告警，需将 app-server-01 迁移至空闲主机 esxi-node04，预计业务中断约 30 秒。",
    action_type: "vm_migrate",
    risk_level: "medium",
    risk_score: 45,
    status: "pending",
    requester: "zhangsan",
    assignee: "ops-lead",
    incident_ref: "INC-20260405-001",
    change_analysis_ref: "cia-001",
    target_object: "app-server-01",
    target_object_type: "VirtualMachine",
    created_at: "2026-04-05T08:50:00Z",
    updated_at: "2026-04-05T08:50:00Z",
    expires_at: "2026-04-05T10:50:00Z",
    decision_comment: null,
    decided_at: null,
    decided_by: null,
    tags: ["vmware", "migration", "incident-driven"],
  },
  {
    id: "APR-20260405-002",
    title: "清理 ds-nfs-prod01 过期快照",
    description: "快照堆积导致容量告警，需批量删除 7 天前快照，预计释放 820GB 空间。",
    action_type: "snapshot_delete",
    risk_level: "low",
    risk_score: 18,
    status: "approved",
    requester: "lisi",
    assignee: "ops-lead",
    incident_ref: "INC-20260405-002",
    change_analysis_ref: null,
    target_object: "ds-nfs-prod01",
    target_object_type: "Datastore",
    created_at: "2026-04-05T07:45:00Z",
    updated_at: "2026-04-05T08:10:00Z",
    expires_at: null,
    decision_comment: "已确认快照列表，允许清理。",
    decided_at: "2026-04-05T08:10:00Z",
    decided_by: "ops-lead",
    tags: ["vmware", "capacity", "cleanup"],
  },
  {
    id: "APR-20260404-005",
    title: "升级 esxi-node01 网卡固件至 v3.11",
    description: "vmnic2 链路中断疑似固件 Bug，需要在维护窗口内升级网卡固件。",
    action_type: "config_change",
    risk_level: "high",
    risk_score: 72,
    status: "rejected",
    requester: "wangwu",
    assignee: "ops-lead",
    incident_ref: "INC-20260404-005",
    change_analysis_ref: null,
    target_object: "esxi-node01",
    target_object_type: "HostSystem",
    created_at: "2026-04-04T14:00:00Z",
    updated_at: "2026-04-04T15:30:00Z",
    expires_at: null,
    decision_comment: "风险过高，需先在测试环境验证，请重新评估后提交。",
    decided_at: "2026-04-04T15:30:00Z",
    decided_by: "ops-lead",
    tags: ["hardware", "firmware", "high-risk"],
  },
  {
    id: "APR-20260405-003",
    title: "执行 cluster-prod-az1 资源池扩容脚本",
    description: "为应对业务增长，需要通过自动化脚本扩展资源池配置。",
    action_type: "script_exec",
    risk_level: "high",
    risk_score: 68,
    status: "pending",
    requester: "zhangsan",
    assignee: null,
    incident_ref: null,
    change_analysis_ref: null,
    target_object: "cluster-prod-az1",
    target_object_type: "ClusterComputeResource",
    created_at: "2026-04-05T09:00:00Z",
    updated_at: "2026-04-05T09:00:00Z",
    expires_at: "2026-04-05T21:00:00Z",
    decision_comment: null,
    decided_at: null,
    decided_by: null,
    tags: ["automation", "cluster", "scaling"],
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: "NTF-001",
    title: "【严重】esxi-node03 CPU 持续 >95%",
    content: "故障事件 INC-20260405-001 已触发，esxi-node03 CPU 利用率持续高于 95% 超过 30 分钟，请立即处理。",
    priority: "urgent",
    status: "acknowledged",
    incident_ref: "INC-20260405-001",
    channels: ["dingtalk", "sms"],
    recipients: ["zhangsan"],
    created_at: "2026-04-05T08:16:30Z",
    delivered_at: "2026-04-05T08:16:35Z",
    acknowledged_at: "2026-04-05T08:45:00Z",
    acknowledged_by: "zhangsan",
    escalation_count: 0,
    next_escalation_at: null,
  },
  {
    id: "NTF-002",
    title: "【中】ds-nfs-prod01 容量告警",
    content: "存储 ds-nfs-prod01 可用空间已低于 10%，请尽快清理快照或扩容。",
    priority: "high",
    status: "delivered",
    incident_ref: "INC-20260405-002",
    channels: ["dingtalk"],
    recipients: ["lisi", "ops-team"],
    created_at: "2026-04-05T07:30:30Z",
    delivered_at: "2026-04-05T07:30:35Z",
    acknowledged_at: null,
    acknowledged_by: null,
    escalation_count: 1,
    next_escalation_at: "2026-04-05T09:30:00Z",
  },
  {
    id: "NTF-003",
    title: "【信息】INC-20260404-005 已解决",
    content: "cluster-prod-az1 HA 切换故障已处理完毕，所有受影响 VM 已恢复正常运行。",
    priority: "normal",
    status: "acknowledged",
    incident_ref: "INC-20260404-005",
    channels: ["dingtalk"],
    recipients: ["lisi", "ops-lead"],
    created_at: "2026-04-05T01:30:00Z",
    delivered_at: "2026-04-05T01:30:05Z",
    acknowledged_at: "2026-04-05T01:31:00Z",
    acknowledged_by: "lisi",
    escalation_count: 0,
    next_escalation_at: null,
  },
  {
    id: "NTF-004",
    title: "【高】审批申请待处理（超时风险）",
    content: "APR-20260405-001 迁移申请已等待超过 1 小时，请及时审批或拒绝。",
    priority: "high",
    status: "escalated",
    incident_ref: null,
    channels: ["wecom", "email"],
    recipients: ["ops-lead"],
    created_at: "2026-04-05T09:50:00Z",
    delivered_at: "2026-04-05T09:50:05Z",
    acknowledged_at: null,
    acknowledged_by: null,
    escalation_count: 2,
    next_escalation_at: "2026-04-05T10:50:00Z",
  },
];

export const mockOnCallShifts: OnCallShift[] = [
  {
    id: "shift-001",
    name: "生产环境 4 月第一周值班",
    team: "运维一组",
    members: ["zhangsan", "lisi"],
    start_at: "2026-04-04T08:00:00Z",
    end_at: "2026-04-07T08:00:00Z",
    active: true,
  },
  {
    id: "shift-002",
    name: "生产环境 4 月第二周值班",
    team: "运维二组",
    members: ["wangwu", "zhaoliu"],
    start_at: "2026-04-07T08:00:00Z",
    end_at: "2026-04-14T08:00:00Z",
    active: false,
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: "AUD-001",
    event_type: "tool_invoked",
    severity: "info",
    actor: "EvidenceCollectionAgent",
    actor_type: "agent",
    action: "vmware.get_host_detail",
    resource_type: "HostSystem",
    resource_id: "host-33",
    resource_name: "esxi-node03",
    outcome: "success",
    reason: null,
    incident_ref: "INC-20260405-001",
    request_id: "req-a1b2c3",
    trace_id: "trc-x1y2z3",
    timestamp: "2026-04-05T08:20:06Z",
    metadata: { duration_ms: 320, gateway: "vmware-skill-gateway" },
  },
  {
    id: "AUD-002",
    event_type: "approval_created",
    severity: "info",
    actor: "zhangsan",
    actor_type: "human",
    action: "create_approval",
    resource_type: "ApprovalRequest",
    resource_id: "APR-20260405-001",
    resource_name: "迁移 app-server-01",
    outcome: "success",
    reason: null,
    incident_ref: "INC-20260405-001",
    request_id: "req-d4e5f6",
    trace_id: "trc-a4b5c6",
    timestamp: "2026-04-05T08:50:00Z",
    metadata: { risk_score: 45 },
  },
  {
    id: "AUD-003",
    event_type: "approval_decided",
    severity: "info",
    actor: "ops-lead",
    actor_type: "human",
    action: "approve",
    resource_type: "ApprovalRequest",
    resource_id: "APR-20260405-002",
    resource_name: "清理 ds-nfs-prod01 快照",
    outcome: "success",
    reason: "已确认快照列表，允许清理",
    incident_ref: "INC-20260405-002",
    request_id: "req-g7h8i9",
    trace_id: "trc-d7e8f9",
    timestamp: "2026-04-05T08:10:00Z",
    metadata: {},
  },
  {
    id: "AUD-004",
    event_type: "policy_hit",
    severity: "warning",
    actor: "Orchestrator",
    actor_type: "agent",
    action: "vmware.vm_migrate",
    resource_type: "VirtualMachine",
    resource_id: "vm-201",
    resource_name: "app-server-01",
    outcome: "blocked",
    reason: "风险评分 45 超过无审批执行阈值 30，已拦截并转入审批队列",
    incident_ref: "INC-20260405-001",
    request_id: "req-j1k2l3",
    trace_id: "trc-g1h2i3",
    timestamp: "2026-04-05T08:49:00Z",
    metadata: { policy_id: "POL-001", risk_score: 45 },
  },
  {
    id: "AUD-005",
    event_type: "execution_completed",
    severity: "info",
    actor: "Orchestrator",
    actor_type: "agent",
    action: "snapshot_delete_batch",
    resource_type: "Datastore",
    resource_id: "ds-45",
    resource_name: "ds-nfs-prod01",
    outcome: "success",
    reason: null,
    incident_ref: "INC-20260405-002",
    request_id: "req-m4n5o6",
    trace_id: "trc-j4k5l6",
    timestamp: "2026-04-05T08:20:00Z",
    metadata: { snapshots_deleted: 14, space_freed_gb: 820 },
  },
];

export const mockKnowledgeArticles: KnowledgeArticle[] = [
  {
    id: "KB-001",
    title: "Java Full GC 风暴导致 vCPU 高占用的诊断方法",
    content_summary: "当 VMware 虚拟机内 Java 应用发生 Full GC 风暴时，会导致宿主机 CPU 利用率骤升。本文介绍诊断步骤：检查 GC 日志、调整堆内存、设置 GC 策略。",
    source: "runbook",
    status: "published",
    tags: ["java", "jvm", "cpu", "gc", "vmware"],
    categories: ["性能", "JVM"],
    author: "ops-team",
    version: "1.2.0",
    hit_count: 23,
    confidence_score: 0.92,
    created_at: "2026-01-10T09:00:00Z",
    updated_at: "2026-03-20T14:30:00Z",
    related_incident_ids: ["INC-20260405-001"],
  },
  {
    id: "KB-002",
    title: "VMware HA 隔离事件处理流程",
    content_summary: "当主机检测到网络隔离时，HA 会按隔离响应策略处理 VM。本文包含隔离响应策略配置、排查步骤和最佳实践。",
    source: "runbook",
    status: "published",
    tags: ["vmware", "ha", "network", "isolation"],
    categories: ["高可用", "VMware"],
    author: "ops-team",
    version: "2.0.1",
    hit_count: 15,
    confidence_score: 0.88,
    created_at: "2025-11-05T10:00:00Z",
    updated_at: "2026-02-14T11:00:00Z",
    related_incident_ids: ["INC-20260404-005"],
  },
  {
    id: "KB-003",
    title: "NFS 数据存储快照容量管理最佳实践",
    content_summary: "快照占用大量存储空间是生产环境常见问题。本文介绍快照保留策略、自动化清理配置和容量规划建议。",
    source: "confluence",
    status: "published",
    tags: ["vmware", "nfs", "snapshot", "capacity"],
    categories: ["容量", "存储"],
    author: "storage-team",
    version: "1.0.3",
    hit_count: 31,
    confidence_score: 0.95,
    created_at: "2025-08-20T08:00:00Z",
    updated_at: "2026-01-08T16:00:00Z",
    related_incident_ids: ["INC-20260405-002"],
  },
  {
    id: "KB-004",
    title: "AI 根因分析结果可解释性指南",
    content_summary: "OpsPilot RCA 模块输出的根因候选置信度计算方式、证据权重说明和人工复核建议。",
    source: "ai_generated",
    status: "reviewing",
    tags: ["aiops", "rca", "explainability"],
    categories: ["AI", "诊断"],
    author: "ai-team",
    version: "0.9.0",
    hit_count: 7,
    confidence_score: 0.71,
    created_at: "2026-03-01T12:00:00Z",
    updated_at: "2026-04-01T09:00:00Z",
    related_incident_ids: [],
  },
];

export const mockKnowledgeImportJobs: KnowledgeImportJob[] = [
  {
    id: "KIJ-001",
    source_type: "confluence",
    source_url: "https://confluence.corp.local/space/OPS",
    status: "completed",
    articles_imported: 48,
    articles_failed: 2,
    started_at: "2026-04-04T02:00:00Z",
    completed_at: "2026-04-04T02:18:00Z",
    error: null,
  },
  {
    id: "KIJ-002",
    source_type: "runbook",
    source_url: "https://gitlab.corp.local/runbooks",
    status: "running",
    articles_imported: 12,
    articles_failed: 0,
    started_at: "2026-04-05T09:00:00Z",
    completed_at: null,
    error: null,
  },
];

export const mockPolicies: OpsPolicy[] = [
  {
    id: "POL-001",
    name: "高风险操作审批门控",
    description: "凡工具调用风险评分超过 30 分的写操作，必须通过人工审批后方可执行，防止 AI 直接执行高风险变更。",
    type: "approval_gate",
    status: "active",
    effect: "require_approval",
    scope: ["vmware.vm_migrate", "vmware.vm_power_off", "script_exec"],
    conditions: { risk_score_gt: 30, action_type: ["write", "delete"] },
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-03-01T12:00:00Z",
    hit_count: 12,
    last_hit_at: "2026-04-05T08:49:00Z",
    author: "security-team",
    version: "1.1.0",
    rego_snippet: 'package opspilot.approval\ndefault require_approval = false\nrequire_approval { input.risk_score > 30 }',
  },
  {
    id: "POL-002",
    name: "生产环境时间窗口限制",
    description: "生产环境写操作仅允许在维护窗口（周三 02:00-06:00）或经审批的变更单内执行。",
    type: "time_window",
    status: "active",
    effect: "deny",
    scope: ["production"],
    conditions: { allowed_hours: { weekday: 3, start: "02:00", end: "06:00" } },
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-02-15T10:00:00Z",
    hit_count: 4,
    last_hit_at: "2026-04-03T14:22:00Z",
    author: "ops-lead",
    version: "1.0.0",
    rego_snippet: null,
  },
  {
    id: "POL-003",
    name: "核心 VM 保护策略",
    description: "标记为 core-service 的虚拟机，禁止通过 AI 直接执行关机和删除操作，只能人工操作。",
    type: "scope_guard",
    status: "active",
    effect: "deny",
    scope: ["vmware.vm_power_off", "vmware.vm_delete"],
    conditions: { vm_tag: "core-service" },
    created_at: "2026-01-15T08:00:00Z",
    updated_at: "2026-01-15T08:00:00Z",
    hit_count: 1,
    last_hit_at: "2026-03-10T10:05:00Z",
    author: "security-team",
    version: "1.0.0",
    rego_snippet: 'package opspilot.scope\ndefault deny = false\ndeny { input.vm_tags[_] == "core-service" }',
  },
  {
    id: "POL-004",
    name: "工具调用频率限制",
    description: "单个 Agent 每分钟最多调用同一工具 10 次，防止意外循环调用导致基础设施过载。",
    type: "rate_limit",
    status: "inactive",
    effect: "deny",
    scope: ["*"],
    conditions: { max_calls_per_minute: 10, per: "agent_tool_pair" },
    created_at: "2026-03-20T00:00:00Z",
    updated_at: "2026-04-01T09:00:00Z",
    hit_count: 0,
    last_hit_at: null,
    author: "platform-team",
    version: "0.9.0",
    rego_snippet: null,
  },
];

export const mockPolicyHits: PolicyHitRecord[] = [
  {
    id: "PHR-001",
    policy_id: "POL-001",
    policy_name: "高风险操作审批门控",
    effect: "require_approval",
    actor: "Orchestrator",
    tool_name: "vmware.vm_migrate",
    resource: "app-server-01",
    outcome: "escalated",
    timestamp: "2026-04-05T08:49:00Z",
    trace_id: "trc-g1h2i3",
  },
  {
    id: "PHR-002",
    policy_id: "POL-003",
    policy_name: "核心 VM 保护策略",
    effect: "deny",
    actor: "Orchestrator",
    tool_name: "vmware.vm_power_off",
    resource: "db-server-01",
    outcome: "blocked",
    timestamp: "2026-03-10T10:05:00Z",
    trace_id: "trc-p1q2r3",
  },
];

export const mockCaseArchives: CaseArchive[] = [
  {
    id: "CASE-20260320",
    title: "Java GC 风暴导致主机 CPU 飙升（已结）",
    summary: "2026-03-20 app-server-03 Java 进程 Full GC 频率过高，导致 esxi-node02 CPU 利用率飙升至 96%。",
    category: "performance",
    status: "archived",
    severity: "high",
    tags: ["jvm", "cpu", "vmware", "gc"],
    incident_refs: ["INC-20260320-001"],
    root_cause_summary: "JVM 堆内存设置过小（-Xmx 512m），应用在高负载下频繁触发 Full GC，导致 STW 暂停期间 vCPU 持续空转。",
    resolution_summary: "将 JVM 堆内存扩展至 -Xmx 4096m，同时启用 G1GC 替代 CMS。调整后 GC 频率降低 95%，CPU 利用率恢复至 35% 以下。",
    lessons_learned: "应将 JVM 堆内存参数纳入标准化部署模板；建议为 Java 应用类 VM 设置 CPU ready time 告警阈值。",
    author: "zhangsan",
    created_at: "2026-03-20T18:00:00Z",
    archived_at: "2026-03-21T09:00:00Z",
    similarity_score: 0.82,
    hit_count: 3,
    knowledge_refs: ["KB-001"],
  },
  {
    id: "CASE-20260315",
    title: "NFS 存储快照堆积导致容量告警",
    summary: "2026-03-15 ds-nfs-staging01 快照未按策略清理，导致可用空间降至 5%，触发 P2 告警。",
    category: "capacity",
    status: "archived",
    severity: "medium",
    tags: ["nfs", "snapshot", "capacity", "vmware"],
    incident_refs: ["INC-20260315-003"],
    root_cause_summary: "快照保留策略配置错误，7 天保留期未生效，导致快照持续累积超过 30 天。",
    resolution_summary: "修正快照策略配置，批量删除过期快照共 24 个，释放空间 1.2TB。",
    lessons_learned: "快照策略应定期审计，建议增加容量预警在 15% 时就提前处理。",
    author: "lisi",
    created_at: "2026-03-15T14:00:00Z",
    archived_at: "2026-03-16T10:00:00Z",
    similarity_score: 0.91,
    hit_count: 5,
    knowledge_refs: ["KB-003"],
  },
  {
    id: "CASE-20260228",
    title: "esxi-node05 HA 切换后 VM 启动顺序异常",
    summary: "2026-02-28 HA 切换后部分 VM 按错误顺序启动，数据库 VM 先于应用层启动导致连接超时。",
    category: "availability",
    status: "archived",
    severity: "critical",
    tags: ["ha", "vmware", "boot-order", "database"],
    incident_refs: ["INC-20260228-002"],
    root_cause_summary: "VM 启动顺序组（Boot Order Group）未正确配置，数据库和应用层处于同一优先级组中。",
    resolution_summary: "重新配置 VM 启动顺序组，将数据库设为最高优先级，应用层延迟 120 秒启动，缓存层再延迟 60 秒。",
    lessons_learned: "HA 环境下必须明确定义 VM 启动顺序，并纳入日常巡检项。",
    author: "wangwu",
    created_at: "2026-02-28T22:00:00Z",
    archived_at: "2026-03-01T09:00:00Z",
    similarity_score: null,
    hit_count: 2,
    knowledge_refs: ["KB-002"],
  },
];

export const mockAgentRuns: AgentRun[] = [
  {
    id: "RUN-001",
    intent: "diagnose_incident",
    status: "completed",
    trigger: "alert",
    incident_ref: "INC-20260405-001",
    session_ref: "sess-001",
    steps: [
      { step_id: "s1", agent_name: "IntentAgent", status: "done", input_summary: "alert: esxi-node03 CPU > 95%", output_summary: '{"intent":"diagnose_incident","slots":{"host":"esxi-node03"}}', tool_calls: 0, started_at: "2026-04-05T08:12:05Z", completed_at: "2026-04-05T08:12:06Z", duration_ms: 380, error: null },
      { step_id: "s2", agent_name: "EvidenceCollectionAgent", status: "done", input_summary: '{"host":"esxi-node03","incident_id":"INC-20260405-001"}', output_summary: "collected 4 evidence items from prometheus + vcenter events", tool_calls: 3, started_at: "2026-04-05T08:12:10Z", completed_at: "2026-04-05T08:15:00Z", duration_ms: 2870, error: null },
      { step_id: "s3", agent_name: "KBRetrievalAgent", status: "done", input_summary: '{"query":"java gc cpu vmware"}', output_summary: "retrieved KB-001: Java Full GC 诊断方法 (confidence: 0.92)", tool_calls: 1, started_at: "2026-04-05T08:15:00Z", completed_at: "2026-04-05T08:15:30Z", duration_ms: 480, error: null },
      { step_id: "s4", agent_name: "RCAAgent", status: "done", input_summary: '{"evidence_refs":["evd-001","evd-002","evd-003","evd-004"],"kb_refs":["KB-001"]}', output_summary: "2 root cause candidates ranked by confidence", tool_calls: 0, started_at: "2026-04-05T08:15:30Z", completed_at: "2026-04-05T08:16:00Z", duration_ms: 510, error: null },
      { step_id: "s5", agent_name: "NotificationAgent", status: "done", input_summary: '{"recipients":["zhangsan"],"channels":["dingtalk","sms"]}', output_summary: "notification delivered to 1 recipient", tool_calls: 1, started_at: "2026-04-05T08:16:00Z", completed_at: "2026-04-05T08:16:30Z", duration_ms: 320, error: null },
    ],
    total_tool_calls: 5,
    total_duration_ms: 4560,
    started_at: "2026-04-05T08:12:05Z",
    completed_at: "2026-04-05T08:16:30Z",
    output_summary: "诊断完成：识别 2 个根因候选，已发送值班通知，等待人工确认后执行建议动作。",
    error: null,
  },
  {
    id: "RUN-002",
    intent: "analyze_change_impact",
    status: "completed",
    trigger: "user",
    incident_ref: "INC-20260405-001",
    session_ref: "sess-001",
    steps: [
      { step_id: "s1", agent_name: "IntentAgent", status: "done", input_summary: "user: 分析迁移 app-server-01 的影响", output_summary: '{"intent":"analyze_change_impact","slots":{"vm":"vm-201","action":"vm_migrate"}}', tool_calls: 0, started_at: "2026-04-05T08:25:05Z", completed_at: "2026-04-05T08:25:06Z", duration_ms: 210, error: null },
      { step_id: "s2", agent_name: "ChangeCorrelationAgent", status: "done", input_summary: '{"target":"vm-201","action":"vm_migrate"}', output_summary: "risk_score: 45 (medium), 3 impacted objects, approval required", tool_calls: 1, started_at: "2026-04-05T08:25:06Z", completed_at: "2026-04-05T08:25:30Z", duration_ms: 520, error: null },
    ],
    total_tool_calls: 1,
    total_duration_ms: 730,
    started_at: "2026-04-05T08:25:05Z",
    completed_at: "2026-04-05T08:25:30Z",
    output_summary: "变更影响分析完成，风险等级：中，建议审批后执行。",
    error: null,
  },
  {
    id: "RUN-003",
    intent: "diagnose_incident",
    status: "running",
    trigger: "alert",
    incident_ref: "INC-20260405-002",
    session_ref: null,
    steps: [
      { step_id: "s1", agent_name: "IntentAgent", status: "done", input_summary: "alert: ds-nfs-prod01 capacity < 10%", output_summary: '{"intent":"diagnose_incident","slots":{"datastore":"ds-45"}}', tool_calls: 0, started_at: "2026-04-05T07:30:35Z", completed_at: "2026-04-05T07:30:36Z", duration_ms: 190, error: null },
      { step_id: "s2", agent_name: "EvidenceCollectionAgent", status: "done", input_summary: '{"datastore":"ds-45"}', output_summary: "collected 1 evidence item", tool_calls: 2, started_at: "2026-04-05T07:30:36Z", completed_at: "2026-04-05T07:31:00Z", duration_ms: 850, error: null },
      { step_id: "s3", agent_name: "RCAAgent", status: "running", input_summary: '{"evidence_refs":["evd-005"]}', output_summary: null, tool_calls: 0, started_at: "2026-04-05T07:31:00Z", completed_at: null, duration_ms: null, error: null },
    ],
    total_tool_calls: 2,
    total_duration_ms: null,
    started_at: "2026-04-05T07:30:35Z",
    completed_at: null,
    output_summary: null,
    error: null,
  },
];

export const mockUpgradePackages: UpgradePackage[] = [
  {
    id: "PKG-001",
    version: "0.2.0",
    release_name: "Arctic Fox",
    description: "OpsPilot P1 版本，新增审批中心、知识管理、策略管理等模块。",
    changelog: [
      "新增审批中心、值班通知、审计中心",
      "新增知识管理与知识导入流程",
      "新增策略管理（OPA 接口预留）",
      "新增 SubAgent 运行视图",
      "UI 全面 polish，统一设计系统",
      "修复 BFF 多个接口 envelope 不一致问题",
    ],
    status: "ready",
    target: "all-services",
    package_size_mb: 128.4,
    requires_restart: true,
    requires_approval: true,
    risk_level: "low",
    released_at: "2026-04-05T00:00:00Z",
    deployed_at: null,
    deployed_by: null,
    rollback_version: "0.1.0",
    environment: "production",
  },
  {
    id: "PKG-002",
    version: "0.1.1",
    release_name: "Patch Hotfix",
    description: "修复 P0 中 evidence-aggregator 高负载下连接超时的问题。",
    changelog: [
      "修复 evidence-aggregator httpx 连接池配置",
      "增加 BFF /health 接口超时重试",
    ],
    status: "deployed",
    target: "api-bff",
    package_size_mb: 8.2,
    requires_restart: false,
    requires_approval: false,
    risk_level: "low",
    released_at: "2026-04-02T10:00:00Z",
    deployed_at: "2026-04-02T14:30:00Z",
    deployed_by: "ops-lead",
    rollback_version: "0.1.0",
    environment: "production",
  },
  {
    id: "PKG-003",
    version: "0.3.0-beta",
    release_name: "Blue Glacier",
    description: "P2 Beta，接入真实 VMware vCenter SDK，移除 mock 层。",
    changelog: [
      "接入 PyVmomi vCenter SDK",
      "实现真实 VMware 指标查询",
      "新增 HA 事件实时订阅",
    ],
    status: "available",
    target: "vmware-skill-gateway",
    package_size_mb: 54.8,
    requires_restart: true,
    requires_approval: true,
    risk_level: "medium",
    released_at: "2026-04-04T08:00:00Z",
    deployed_at: null,
    deployed_by: null,
    rollback_version: "0.2.0",
    environment: "staging",
  },
];

export const mockDeploymentHistory: UpgradeDeploymentRecord[] = [
  {
    id: "DEP-001",
    package_id: "PKG-002",
    package_version: "0.1.1",
    status: "deployed",
    environment: "production",
    deployed_by: "ops-lead",
    started_at: "2026-04-02T14:28:00Z",
    completed_at: "2026-04-02T14:30:00Z",
    log_summary: [
      "拉取镜像 opspilot/api-bff:0.1.1",
      "健康检查通过",
      "滚动更新完成，0 中断",
    ],
    rollback_available: true,
  },
];
